//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upcLookUp.UPCSearch {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://searchupc.com/", ConfigurationName="UPCSearch.UPCSearchSoap")]
    public interface UPCSearchSoap {
        
        // CODEGEN: Generating message contract since element name upc from namespace http://searchupc.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://searchupc.com/GetProduct", ReplyAction="*")]
        upcLookUp.UPCSearch.GetProductResponse GetProduct(upcLookUp.UPCSearch.GetProductRequest request);
        
        // CODEGEN: Generating message contract since element name upc from namespace http://searchupc.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://searchupc.com/GetProductJSON", ReplyAction="*")]
        upcLookUp.UPCSearch.GetProductJSONResponse GetProductJSON(upcLookUp.UPCSearch.GetProductJSONRequest request);
        
        // CODEGEN: Generating message contract since element name upc from namespace http://searchupc.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://searchupc.com/Validate", ReplyAction="*")]
        upcLookUp.UPCSearch.ValidateResponse Validate(upcLookUp.UPCSearch.ValidateRequest request);
        
        // CODEGEN: Generating message contract since element name upce from namespace http://searchupc.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://searchupc.com/ConvertToUPCA", ReplyAction="*")]
        upcLookUp.UPCSearch.ConvertToUPCAResponse ConvertToUPCA(upcLookUp.UPCSearch.ConvertToUPCARequest request);
        
        // CODEGEN: Generating message contract since element name upc from namespace http://searchupc.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://searchupc.com/GenerateBarcode", ReplyAction="*")]
        upcLookUp.UPCSearch.GenerateBarcodeResponse GenerateBarcode(upcLookUp.UPCSearch.GenerateBarcodeRequest request);
        
        // CODEGEN: Generating message contract since element name upc from namespace http://searchupc.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://searchupc.com/SuggestProduct", ReplyAction="*")]
        upcLookUp.UPCSearch.SuggestProductResponse SuggestProduct(upcLookUp.UPCSearch.SuggestProductRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProduct", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.GetProductRequestBody Body;
        
        public GetProductRequest() {
        }
        
        public GetProductRequest(upcLookUp.UPCSearch.GetProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GetProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accesstoken;
        
        public GetProductRequestBody() {
        }
        
        public GetProductRequestBody(string upc, string accesstoken) {
            this.upc = upc;
            this.accesstoken = accesstoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductResponse", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.GetProductResponseBody Body;
        
        public GetProductResponse() {
        }
        
        public GetProductResponse(upcLookUp.UPCSearch.GetProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GetProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProductResult;
        
        public GetProductResponseBody() {
        }
        
        public GetProductResponseBody(string GetProductResult) {
            this.GetProductResult = GetProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductJSON", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.GetProductJSONRequestBody Body;
        
        public GetProductJSONRequest() {
        }
        
        public GetProductJSONRequest(upcLookUp.UPCSearch.GetProductJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GetProductJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accesstoken;
        
        public GetProductJSONRequestBody() {
        }
        
        public GetProductJSONRequestBody(string upc, string accesstoken) {
            this.upc = upc;
            this.accesstoken = accesstoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductJSONResponse", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.GetProductJSONResponseBody Body;
        
        public GetProductJSONResponse() {
        }
        
        public GetProductJSONResponse(upcLookUp.UPCSearch.GetProductJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GetProductJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProductJSONResult;
        
        public GetProductJSONResponseBody() {
        }
        
        public GetProductJSONResponseBody(string GetProductJSONResult) {
            this.GetProductJSONResult = GetProductJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validate", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.ValidateRequestBody Body;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(upcLookUp.UPCSearch.ValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class ValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accesstoken;
        
        public ValidateRequestBody() {
        }
        
        public ValidateRequestBody(string upc, string accesstoken) {
            this.upc = upc;
            this.accesstoken = accesstoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateResponse", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.ValidateResponseBody Body;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(upcLookUp.UPCSearch.ValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class ValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateResult;
        
        public ValidateResponseBody() {
        }
        
        public ValidateResponseBody(string ValidateResult) {
            this.ValidateResult = ValidateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToUPCARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToUPCA", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.ConvertToUPCARequestBody Body;
        
        public ConvertToUPCARequest() {
        }
        
        public ConvertToUPCARequest(upcLookUp.UPCSearch.ConvertToUPCARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class ConvertToUPCARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upce;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accesstoken;
        
        public ConvertToUPCARequestBody() {
        }
        
        public ConvertToUPCARequestBody(string upce, string accesstoken) {
            this.upce = upce;
            this.accesstoken = accesstoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToUPCAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToUPCAResponse", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.ConvertToUPCAResponseBody Body;
        
        public ConvertToUPCAResponse() {
        }
        
        public ConvertToUPCAResponse(upcLookUp.UPCSearch.ConvertToUPCAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class ConvertToUPCAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertToUPCAResult;
        
        public ConvertToUPCAResponseBody() {
        }
        
        public ConvertToUPCAResponseBody(string ConvertToUPCAResult) {
            this.ConvertToUPCAResult = ConvertToUPCAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateBarcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateBarcode", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.GenerateBarcodeRequestBody Body;
        
        public GenerateBarcodeRequest() {
        }
        
        public GenerateBarcodeRequest(upcLookUp.UPCSearch.GenerateBarcodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GenerateBarcodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upc;
        
        public GenerateBarcodeRequestBody() {
        }
        
        public GenerateBarcodeRequestBody(string upc) {
            this.upc = upc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateBarcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateBarcodeResponse", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.GenerateBarcodeResponseBody Body;
        
        public GenerateBarcodeResponse() {
        }
        
        public GenerateBarcodeResponse(upcLookUp.UPCSearch.GenerateBarcodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class GenerateBarcodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateBarcodeResult;
        
        public GenerateBarcodeResponseBody() {
        }
        
        public GenerateBarcodeResponseBody(string GenerateBarcodeResult) {
            this.GenerateBarcodeResult = GenerateBarcodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestProduct", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.SuggestProductRequestBody Body;
        
        public SuggestProductRequest() {
        }
        
        public SuggestProductRequest(upcLookUp.UPCSearch.SuggestProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class SuggestProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string upc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string productnamewithmanufacturer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string productattribute;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accesstoken;
        
        public SuggestProductRequestBody() {
        }
        
        public SuggestProductRequestBody(string upc, string productnamewithmanufacturer, string productattribute, string accesstoken) {
            this.upc = upc;
            this.productnamewithmanufacturer = productnamewithmanufacturer;
            this.productattribute = productattribute;
            this.accesstoken = accesstoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuggestProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuggestProductResponse", Namespace="http://searchupc.com/", Order=0)]
        public upcLookUp.UPCSearch.SuggestProductResponseBody Body;
        
        public SuggestProductResponse() {
        }
        
        public SuggestProductResponse(upcLookUp.UPCSearch.SuggestProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://searchupc.com/")]
    public partial class SuggestProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SuggestProductResult;
        
        public SuggestProductResponseBody() {
        }
        
        public SuggestProductResponseBody(string SuggestProductResult) {
            this.SuggestProductResult = SuggestProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPCSearchSoapChannel : upcLookUp.UPCSearch.UPCSearchSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPCSearchSoapClient : System.ServiceModel.ClientBase<upcLookUp.UPCSearch.UPCSearchSoap>, upcLookUp.UPCSearch.UPCSearchSoap {
        
        public UPCSearchSoapClient() {
        }
        
        public UPCSearchSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPCSearchSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCSearchSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCSearchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        upcLookUp.UPCSearch.GetProductResponse upcLookUp.UPCSearch.UPCSearchSoap.GetProduct(upcLookUp.UPCSearch.GetProductRequest request) {
            return base.Channel.GetProduct(request);
        }
        
        public string GetProduct(string upc, string accesstoken) {
            upcLookUp.UPCSearch.GetProductRequest inValue = new upcLookUp.UPCSearch.GetProductRequest();
            inValue.Body = new upcLookUp.UPCSearch.GetProductRequestBody();
            inValue.Body.upc = upc;
            inValue.Body.accesstoken = accesstoken;
            upcLookUp.UPCSearch.GetProductResponse retVal = ((upcLookUp.UPCSearch.UPCSearchSoap)(this)).GetProduct(inValue);
            return retVal.Body.GetProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        upcLookUp.UPCSearch.GetProductJSONResponse upcLookUp.UPCSearch.UPCSearchSoap.GetProductJSON(upcLookUp.UPCSearch.GetProductJSONRequest request) {
            return base.Channel.GetProductJSON(request);
        }
        
        public string GetProductJSON(string upc, string accesstoken) {
            upcLookUp.UPCSearch.GetProductJSONRequest inValue = new upcLookUp.UPCSearch.GetProductJSONRequest();
            inValue.Body = new upcLookUp.UPCSearch.GetProductJSONRequestBody();
            inValue.Body.upc = upc;
            inValue.Body.accesstoken = accesstoken;
            upcLookUp.UPCSearch.GetProductJSONResponse retVal = ((upcLookUp.UPCSearch.UPCSearchSoap)(this)).GetProductJSON(inValue);
            return retVal.Body.GetProductJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        upcLookUp.UPCSearch.ValidateResponse upcLookUp.UPCSearch.UPCSearchSoap.Validate(upcLookUp.UPCSearch.ValidateRequest request) {
            return base.Channel.Validate(request);
        }
        
        public string Validate(string upc, string accesstoken) {
            upcLookUp.UPCSearch.ValidateRequest inValue = new upcLookUp.UPCSearch.ValidateRequest();
            inValue.Body = new upcLookUp.UPCSearch.ValidateRequestBody();
            inValue.Body.upc = upc;
            inValue.Body.accesstoken = accesstoken;
            upcLookUp.UPCSearch.ValidateResponse retVal = ((upcLookUp.UPCSearch.UPCSearchSoap)(this)).Validate(inValue);
            return retVal.Body.ValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        upcLookUp.UPCSearch.ConvertToUPCAResponse upcLookUp.UPCSearch.UPCSearchSoap.ConvertToUPCA(upcLookUp.UPCSearch.ConvertToUPCARequest request) {
            return base.Channel.ConvertToUPCA(request);
        }
        
        public string ConvertToUPCA(string upce, string accesstoken) {
            upcLookUp.UPCSearch.ConvertToUPCARequest inValue = new upcLookUp.UPCSearch.ConvertToUPCARequest();
            inValue.Body = new upcLookUp.UPCSearch.ConvertToUPCARequestBody();
            inValue.Body.upce = upce;
            inValue.Body.accesstoken = accesstoken;
            upcLookUp.UPCSearch.ConvertToUPCAResponse retVal = ((upcLookUp.UPCSearch.UPCSearchSoap)(this)).ConvertToUPCA(inValue);
            return retVal.Body.ConvertToUPCAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        upcLookUp.UPCSearch.GenerateBarcodeResponse upcLookUp.UPCSearch.UPCSearchSoap.GenerateBarcode(upcLookUp.UPCSearch.GenerateBarcodeRequest request) {
            return base.Channel.GenerateBarcode(request);
        }
        
        public string GenerateBarcode(string upc) {
            upcLookUp.UPCSearch.GenerateBarcodeRequest inValue = new upcLookUp.UPCSearch.GenerateBarcodeRequest();
            inValue.Body = new upcLookUp.UPCSearch.GenerateBarcodeRequestBody();
            inValue.Body.upc = upc;
            upcLookUp.UPCSearch.GenerateBarcodeResponse retVal = ((upcLookUp.UPCSearch.UPCSearchSoap)(this)).GenerateBarcode(inValue);
            return retVal.Body.GenerateBarcodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        upcLookUp.UPCSearch.SuggestProductResponse upcLookUp.UPCSearch.UPCSearchSoap.SuggestProduct(upcLookUp.UPCSearch.SuggestProductRequest request) {
            return base.Channel.SuggestProduct(request);
        }
        
        public string SuggestProduct(string upc, string productnamewithmanufacturer, string productattribute, string accesstoken) {
            upcLookUp.UPCSearch.SuggestProductRequest inValue = new upcLookUp.UPCSearch.SuggestProductRequest();
            inValue.Body = new upcLookUp.UPCSearch.SuggestProductRequestBody();
            inValue.Body.upc = upc;
            inValue.Body.productnamewithmanufacturer = productnamewithmanufacturer;
            inValue.Body.productattribute = productattribute;
            inValue.Body.accesstoken = accesstoken;
            upcLookUp.UPCSearch.SuggestProductResponse retVal = ((upcLookUp.UPCSearch.UPCSearchSoap)(this)).SuggestProduct(inValue);
            return retVal.Body.SuggestProductResult;
        }
    }
}
